// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgGfCjvSChu6P9r_PbXzhEvm2GwKfcez4',
    appId: '1:356142583978:web:99386e69c2bcc8dee980d3',
    messagingSenderId: '356142583978',
    projectId: 'smart-flat-18af0',
    authDomain: 'smart-flat-18af0.firebaseapp.com',
    storageBucket: 'smart-flat-18af0.firebasestorage.app',
    measurementId: 'G-XGWKFKCF2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUFmuqregXDYEu7wSL6SY_rdic_S28Phw',
    appId: '1:356142583978:android:581115f4fddddf3be980d3',
    messagingSenderId: '356142583978',
    projectId: 'smart-flat-18af0',
    storageBucket: 'smart-flat-18af0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpAQfZIWwn2QdCVehW5oI6DitATLawTDc',
    appId: '1:356142583978:ios:e723bcf6e0a9884be980d3',
    messagingSenderId: '356142583978',
    projectId: 'smart-flat-18af0',
    storageBucket: 'smart-flat-18af0.firebasestorage.app',
    iosBundleId: 'com.example.smartFlat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpAQfZIWwn2QdCVehW5oI6DitATLawTDc',
    appId: '1:356142583978:ios:e723bcf6e0a9884be980d3',
    messagingSenderId: '356142583978',
    projectId: 'smart-flat-18af0',
    storageBucket: 'smart-flat-18af0.firebasestorage.app',
    iosBundleId: 'com.example.smartFlat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgGfCjvSChu6P9r_PbXzhEvm2GwKfcez4',
    appId: '1:356142583978:web:0e534b7b1c39f348e980d3',
    messagingSenderId: '356142583978',
    projectId: 'smart-flat-18af0',
    authDomain: 'smart-flat-18af0.firebaseapp.com',
    storageBucket: 'smart-flat-18af0.firebasestorage.app',
    measurementId: 'G-6RRT78QNT8',
  );
}
